# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='weather.proto',
  package='kddcup',
  serialized_pb='\n\rweather.proto\x12\x06kddcup\"\xbb\x01\n\x07Weather\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04hour\x18\x02 \x01(\x05\x12\x10\n\x08pressure\x18\x03 \x01(\x02\x12\x14\n\x0csea_pressure\x18\x04 \x01(\x02\x12\x16\n\x0ewind_direction\x18\x05 \x01(\x02\x12\x12\n\nwind_speed\x18\x06 \x01(\x02\x12\x13\n\x0btemperature\x18\x07 \x01(\x02\x12\x14\n\x0crel_humidity\x18\x08 \x01(\x02\x12\x15\n\rprecipitation\x18\t \x01(\x02')




_WEATHER = descriptor.Descriptor(
  name='Weather',
  full_name='kddcup.Weather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='date', full_name='kddcup.Weather.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hour', full_name='kddcup.Weather.hour', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pressure', full_name='kddcup.Weather.pressure', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sea_pressure', full_name='kddcup.Weather.sea_pressure', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wind_direction', full_name='kddcup.Weather.wind_direction', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wind_speed', full_name='kddcup.Weather.wind_speed', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temperature', full_name='kddcup.Weather.temperature', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rel_humidity', full_name='kddcup.Weather.rel_humidity', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='precipitation', full_name='kddcup.Weather.precipitation', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['Weather'] = _WEATHER

class Weather(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEATHER
  
  # @@protoc_insertion_point(class_scope:kddcup.Weather)

# @@protoc_insertion_point(module_scope)
